### DISCUSSION TITLE
[Feature Request] HomeAssistant companion app notifications

### DISCUSSION THREAD

**Discussion by talKitron** [donetick/donetick#111] [Ideas]
Would it be possible to allow linking between a DoneTick user and a HomeAssistant user, or inputting a HomeAssistant notification group name, and send the notifications through the HomeAssistant companion app directly?

**Comment by janstadt** [comment]
This would be great

**Reply by rh535** [reply]
This sounds great if possible.

**Comment by phobiac** [comment]
edit: Thanks to the new and improved integration you only need to set up the integration once for the account that manages the donetick circle, be sure to have it populate individual lists during the setup. The blueprint still works great.

I wanted to share how I've achieved this in a multi-person household.

Using [this Home Assistant integration](https://github.com/donetick/donetick-hass-integration) I set up a list for each user in donetick. To do this you generate an API key in donetick (found under the settings menu) for the user you want to add and provide that key to the integration during setup. Do this for each user and rename the todo entity information accordingly, it will auto generate with a unique text string at first.

For notifications, I used this blueprint:
https://community.home-assistant.io/t/restart-safe-to-do-list-chore-notifications/734132

It has the benefit of choosing if you want to be notified when the task is due, or at a specific time each day.

**Reply by flecmart** [reply]
@phobiac 

Do you have any more tips on how to implement a multi-person household? Basically I have recurring chores that should be done by alternating assignees. I then only want to notify the currently assigend person... however, setting up the hacs integraion and multiple users with api keys, always pulls all the tasks for all the persons. Did you find a way to show only tasks that are assigned to a person?

**Reply by phobiac** [reply]
Unfortunately that seems to not be possible with how the integration is written currently. See my comment here https://github.com/donetick/donetick-hass-integration/issues/14#issuecomment-2938629268

We've just been using this setup for notifications and then checking in Donetick if the task is assigned to us or not for ones with multiple possible assignees.

**Reply by LXDynamics** [reply]
I'm in the process of building out notifications in Home Assistant based on the Webhooks trigger. I think it can be fairly powerful since the trigger can pass the user_IDs to whom the task has been assigned. That can let you filter who to notify using the Choose building block.

**Reply by flecmart** [reply]
Can you share if you have implemented something that works? I also started playing around with the webhooks trigger but did not end up with something that worked well enough for me

**Reply by LXDynamics** [reply]
Hey! Yeah, I think I've got the start of something workable. I'm only one person, but I think these concepts would be expandable to include things like notifying parents if children have completed their tasks, etc.

There are plenty of bugs to work out, but so far I've been able to get reliable completion, reminders and overdue nagging notifications through the Home Assistant mobile app.

Here's the yaml for my automation:

```
alias: DoneTick Notifications
description: >-
  Webhook triggered notification automation for Donetick tasks that have been
  completed, are due or have been skipped.
triggers:
  - trigger: webhook
    allowed_methods:
      - POST
    local_only: true
    webhook_id: "YOUR-ID-GENERATED-BY-TRIGGER"
conditions: []
actions:
  - variables:
      type: |
        {{ trigger.json.type }}
      chore: |
        {{ trigger.json.data.chore }}
      user: |
        {{ trigger.json.data.display_name }}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ type == 'task.completed' }}"
        sequence:
          - action: notify.notify
            metadata: {}
            data:
              message: "{{  chore['name']  }} has been completed by {{ user }}"
              title: Done Tick
      - conditions:
          - condition: template
            value_template: "{{ type == 'task.skipped' }}"
        sequence:
          - action: notify.notify
            metadata: {}
            data:
              message: "{{  chore['name']  }} was skipped by {{ user }}"
              title: Done Tick
      - conditions:
          - condition: template
            value_template: "{{ type == 'task.reminder' }}"
        sequence:
          - variables:
              task_name: |
                {{ trigger.json.data.name }}
              user: |
                {{ trigger.json.data.assignee }}
              date: |
                {{ strptime(trigger.json.data.due_date,  '%Y-%m-%dT%H:%M:%SZ')
                }}
              delta: |
                {% set fmt = '%Y-%m-%dT%H:%M:%SZ' %}
                {% set now = now() %}
                {% set due = date %}
                {{ as_timestamp(due) - as_timestamp(now)}}
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ delta < -100 }}"
                sequence:
                  - action: notify.notify
                    metadata: {}
                    data:
                      message: >-
                        {{  task_name  }} is due to be completed by {{ user }}
                        in {{ time_until(date, 2) }}
                      title: Done Tick
              - conditions:
                  - condition: template
                    value_template: "{{ delta > 100 }}"
                sequence:
                  - action: notify.notify
                    metadata: {}
                    data:
                      message: >-
                        {{  task_name  }} was due to be completed by {{ user }}
                        {{ time_since(date, 2) }} ago.
                      title: Done Tick
              - conditions:
                  - condition: template
                    value_template: "{{ delta < 100 and delta > -100 }}"
                sequence:
                  - action: notify.notify
                    metadata: {}
                    data:
                      message: "{{  task_name  }} is due to be completed by {{ user }}."
                      title: Done Tick
mode: parallel
max: 10
```
