### ISSUE TITLE
Docker Compose Error

### ISSUE THREAD

**Issue by rubenssoto** [donetick/donetick#102]
**Describe the bug**
I got an error when I tried to run the docker compose.

donetick.com/core/config.LoadConfig()
donetick  | 	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
donetick  | main.main()
donetick  | 	/home/runner/work/donetick/donetick/main.go:50 +0xd3
donetick  | --ConfigLoad config for environment: selfhosted panic: Config File "selfhosted" Not Found in "[/config]"

My docker compose:

services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    networks:
      - container-network
    ports:
      - 2021
    volumes:
      - /data/apps/donetick/data:/donetick-data
      - /data/apps/donetick/config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
networks:
  container-network:
    external: true

**Comment by danielrosehill** [comment]
Same!

```
panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 9panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 9panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 9panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 9panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 9panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 9panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 9panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 9panic: Config File "selfhosted" Not Found in "[/config]"
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
	/home/runner/work/donetick/donetick/config/config.go:135 +0x35d
main.main()
	/home/runner/work/donetick/donetick/main.go:50 +0xd3
--ConfigLoad config for environment: selfhosted 
```

I tried manually creating the config file and adding permissions and re-clearing the data mount directory but nothing worked.

**Comment by meauxt** [comment]
can you share the folder structure? I just clone the repo and copy the docker-compose.yml from the readme

here is the folder structure :
```
├── config
│   └── selfhosted.yaml
├── data
│   └── donetick.db
└── docker-compose.yml

```

docker-compose.yml
```yaml
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - ./data:/donetick-data
      - ./config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
```

and selfhosted.yaml copied from [here](https://github.com/donetick/donetick/blob/main/config/selfhosted.yaml)
```yaml
name: "selfhosted"
is_done_tick_dot_com: false
is_user_creation_disabled: false
telegram:
  token: ""
pushover:
  token: ""
database:
  type: "sqlite"
  migration: true
jwt:
  secret: "secret"
  session_time: 168h
  max_refresh: 168h
server:
  port: 2021
  read_timeout: 10s
  write_timeout: 10s
  rate_period: 60s
  rate_limit: 300
  cors_allow_origins:
    - "http://localhost:5173"
    - "http://localhost:7926"
    # the below are required for the android app to work
    - "https://localhost"
    - "capacitor://localhost"
  serve_frontend: true
scheduler_jobs:
  due_job: 30m
  overdue_job: 3h
  pre_due_job: 3h
email:
  host: 
  port: 
  key: 
  email:  
  appHost:  

```
