### ISSUE TITLE
Marking item as completed not working

### ISSUE THREAD

**Issue by fsmeets84** [donetick/donetick#106]
I have Donetick running in a Docker container with the following docker-compose file:

```
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    volumes:
      - /volume1/docker/donetick/data:/donetick-data
      - /volume1/docker/donetick/config:/config
    ports:
      - 2021:2021
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
```

I have added an item on the Home page with a due date of tomorrow.
When I click on the green tick circle, I get a message in the lower right corner: Task will be marked as completed in 3 seconds.
However afterwards it still shows the task as "open".

I have check the container log and it shows the following error message:
**Error scheduling next due date: invalid frequency type, cannot calculate next due date**

Not sure if this is a bug or missing a setting.
