### ISSUE TITLE
[documentation] Add quick start guide for selfhosted edition

### ISSUE THREAD

**Issue by Bartrpc** [donetick/donetick#12]
Hi, 

Could You add quick start guide to your github repo ? Also there will be nice to see some explanation to selfhosted.yaml and name values  :)

Cheers :)

**Comment by PrzemekSkw** [comment]
Hi, I also want to try but webUI don't work when I try with docker. Cannot find any docs how to fill selfhosted.yaml to make it work.
Regards.

**Comment by juanlufont** [comment]
I made some modifications to the docker compose file so the image was pull from DockerHub (only tag available is `latest`). This worked for me:

```
---
version: '3.3'

services:
  app:
    image: donetick/donetick:latest
    container_name: donetick-core
    restart: unless-stopped
    # volumes:
    # # sqlite database:
    #   - ./data:/usr/src/app/data
    ports:
      - "8085:2021"
    hostname: donetick-core
```
For the sake of testing I did not use a volume for the SQLite database. I also had to adjust the port, donetick was actually listeining on port TCP 2021 in the image available on DockerHub

**Comment by meauxt** [comment]
Hi @Bartrpc I just updated the README with an example!

**Comment by accforgithubtest** [comment]
Is any other database supported other than sqlite ? 

If yes, can you also please add an example `config.yaml` for postgres, so we know what the configuration for a database should look like.

**Comment by meauxt** [comment]
@accforgithubtest gonna keep PostgreSQL support unofficial for the time being. but here is a configuration example 
```
database:
  type: "postgres"
  host: "postgres-ip-address"
  port: 5432
  user: db_username
  password: somepassword
  name: somename
  migration: true

```
