### ISSUE TITLE
Lost everything after upgrading

### ISSUE THREAD

**Issue by luke3579** [donetick/donetick#126]
Hi, i’m on the latest release - v0.1.34, I noticed after upgrading the docker image, that all my tasks were deleted, both completed and pending tasks. I noticed the same upgrading to version 0.0.32, but I put this down to configuring authentik. The first time round I was signing in with a local account (not authentik like the second time round)

Here is my docker compose file

```
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    #ports:
    #- 2021:2021
    networks:
      - npm_proxy_network
    volumes:
      - ./data:/usr/src/app/data
      - ./config:/config
    environment:
      - DT_ENV=selfhosted
networks:
  npm_proxy_network:
    external: true
```

I’m not seeing any logs anywhere in donetick so If you need anything else, let me know :)

**Comment by meauxt** [comment]
I'm sorry that happened. can't think what could caused it.  As long as your ./data directory, containing the SQLite database, is properly mounted as a volume, your data should persist outside the container. let's see if someone has better idea of what could happened here. if you can share your docker-compose logs I might have better idea

**Comment by luke3579** [comment]
Hi, i think i sorted it

here's my new docker compose file
it could have been the data volume mapped wrong, or i needed the sqlite_path enviroment vriable. either way, changed the compose file, added in a test chore/task, updated donetick to 1.35 from 1.34 and the test chore/task i made was there. 

```
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    #ports:
      #- 2021:2021
    volumes:
      - ./data:/donetick-data
      - ./config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
    networks:
      - npm_proxy_network
networks:
  npm_proxy_network:
    external: true
```
Thanks so much for this great project :)
