### ISSUE TITLE
SSO login button disapeared with version v0.1.43

### ISSUE THREAD

**Issue by EHRETic** [donetick/donetick#194]
Hi there,

Pretty new to Donetick but I really love it.

I just noticed that my SSO login button (Authentik) is disappearing with version v0.1.43.
Rolling back v0.1.38 brings the button back.

For testing, I always used an incognito tab to confirm that behavior as cached files tends to disturb the testing (on computer already used, I can still see the button until I hit refresh, and when rollbacked to v0.1.38, the button is still not there)

Config (selfhosted):

```
name: "Donetick"
is_done_tick_dot_com: false
is_user_creation_disabled: false
telegram:
  token: ""
pushover:
  token: ""
database:
  type: "postgres"
  migration: true
  # these are only required for postgres
  host: "192.168.X.Y"
  port: 5432
  user: "xxx"
  password: "xxx"
  name: "xxx"
    #jwt:
    # secret: "secret"
    # session_time: 168h
    #  max_refresh: 168h
server:
  port: 3000
  read_timeout: 10s
  write_timeout: 10s
  rate_period: 60s
  rate_limit: 300
  cors_allow_origins:
    - "https://tasks.mydomain"
    # the below are required for the android app to work
    - "https://localhost"
    - "capacitor://localhost"
  serve_frontend: true
scheduler_jobs:
  due_job: 30m
  overdue_job: 3h
  pre_due_job: 3h
email:
  host:
  port:
  key:
  email:
  appHost:
oauth2:
  client_id: "xxx"
  client_secret: "xxx"
  auth_url: "https://auth.mydomain/application/o/authorize/"
  token_url: "https://auth.mydomain/application/o/token/"
  user_info_url: "https://auth.mydomain/application/o/userinfo/"
  redirect_url: "https://tasks.mydomain/auth/oauth2"
  scopes:
    - openid
    - profile
    - email
  name: "Authentik"
```

Thanks in advance for your help! 😉
