### ISSUE TITLE
exec /donetick: exec format error

### ISSUE THREAD

**Issue by Deadman69** [donetick/donetick#33]
Hello,

I have create a fresh `docker-compose.yml` file with the following content (as per the readme) 

```yaml
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021 # needed for serving backend and frontend
    volumes:
      - ./data:/donetick-data # database file stored (sqlite database)
      - ./config:/config # configration file like selfhosted.yaml
    environment:
      - DT_ENV=selfhosted # this tell donetick to load ./config/selfhosted.yaml for the configuration file
      - DT_SQLITE_PATH=/donetick-data/donetick.db
```

But when I run `docker compose up -d`, my container keep restarting and giving me the following logs :
```
deadman@raspberrypi:~/home-server/donetick $ docker logs donetick

exec /donetick: exec format error
exec /donetick: exec format error
exec /donetick: exec format error
exec /donetick: exec format error
exec /donetick: exec format error
exec /donetick: exec format error
exec /donetick: exec format error
exec /donetick: exec format error
exec /donetick: exec format error
exec /donetick: exec format error
```

I use the prebuilt image that i have pull using `docker pull donetick/donetick`
![image](https://github.com/user-attachments/assets/98c4ed13-3880-47a1-a669-ae1a412aefb5)
