### ISSUE TITLE
Docker compose setup

### ISSUE THREAD

**Issue by OBoudreaux** [donetick/donetick#54]
Container pull doesn't pull `./config/selfhosted.yaml` even if `DT_ENV: selfhosted` at least if  PUID/PGID are set in the compose file. I didn't try it without them.

A wget of the config file from the repo has it up and running though.

**Comment by meauxt** [comment]
What docker-compose you are using? can you make sure you are using the one in the readme?
```
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - ./data:/donetick-data
      - ./config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
      
      ```
