### ISSUE TITLE
How to change the android urls in selfhosted.yaml from the docker image on dockerhub

### ISSUE THREAD

**Issue by rmblau** [donetick/donetick#70]
As the title says, how do I change the values in the selfhosted.yaml file in the prebuilt container? Are there env variables I am unaware of that can be used?

**Comment by DeniTCH** [comment]
Hi @rmblau,

If you are using the docker compose file, as described in the documentation:

```yaml
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - ./data:/donetick-data
      - ./config:/config
    environment:
      - DT_ENV=selfhosted
      - DT_SQLITE_PATH=/donetick-data/donetick.db
```

then the selfhosted.yaml file should be in the .config folder, or whichever folder you have specified instead of ".config". In my setup this file was not automatically created and I had to place the file there manually, I just copied it from the "config" folder in the repository.

I hope this helps :)

Best regards,
@DeniTCH
