### ISSUE TITLE
Issues with the Docker Compose file

### ISSUE THREAD

**Issue by rubylaser** [donetick/donetick#8]
I was excited to try this out, because it looks so great. But, I’m trying to get this up and running in docker in my homelab. I’ve noticed the Dockerfile builds to /docktick, but the compose file is looking for /docktick-core. Also, the Dockerfile is exposing port 2021 but the compose file is exposing 8000. Even after correcting these issues, I’m still getting errors when I run the compose. 
```
goroutine 1 [running]:
donetick.com/core/config.LoadConfig()
        /home/runner/work/donetick/donetick/config/config.go:122 +0x311
main.main()
        /home/runner/work/donetick/donetick/main.go:45 +0xb2
--ConfigLoad config for environment: prod panic: Config File "prod" Not Found in "[/config]”
```
there is no prod file in the config directory and I see no mention of how to format it or what variables it should contain unless, I’m supposed to use the selfhosted.yaml file for that. So… some directions to get this container actually working would be awesome!

**Comment by megacorvega** [comment]
@rubylaser Changing the compose file to the following:
```
version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: donetick-core
    restart: unless-stopped

    volumes:
    # sqlite database:
      - ./data:/usr/src/app/data
      - ./config:/config

    ports:
      - "8087:2021"
    environment:
      - DT_ENV=prod
    hostname: donetick-core
    command: ["/donetick"]  # Command to execute your binary inside the container
networks:
  default:
```

and renaming the `selfhosted.yaml` to `prod.yaml` in the locally mounted `config` folder got it up and running for me.

**Comment by meauxt** [comment]
Hi there! 
@rubylaser yeah sorry, the `docker-compose` is not yet listed as a way to run Donetick ( current docker-file I used for different purpose with donetick.com). I will update the I will add a separate `docker-compose` file and update read me instruction!

but in the meantime you can run it with the following commands:
`docker pull donetick/donetick`
`docker run donetick/donetick -p 2021:2021`

or if you want docker-file what @megacorvega  should work, you can change `DT_ENV=prod` to `DT_ENV=selfhosted` and not rename the file 

here it's modified : 
```
version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: donetick-core
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data
      - ./config:/config
    ports:
      - "2021:2021"
    environment:
      - DT_ENV=selfhosted
    hostname: donetick-core
    command: ["/donetick"]  
networks:
  default:
```

**Comment by rubylaser** [comment]
Thanks for the quick response. This got me up and running. It’s looking great now!

**Comment by rubylaser** [comment]
One other thing. I’d like to be able to change the jwt to something other than “secret”. Doing so, causes an invalid signature error.
```
2024-11-23T04:53:12.274Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode401messagesignature is invalid
```

**Comment by rubylaser** [comment]
> Hi there! @rubylaser yeah sorry, the `docker-compose` is not yet listed as a way to run Donetick ( current docker-file I used for different purpose with donetick.com). I will update the I will add a separate `docker-compose` file and update read me instruction!
> 
> but in the meantime you can run it with the following commands: `docker pull donetick/donetick` `docker run donetick/donetick -p 2021:2021`
> 
> or if you want docker-file what @megacorvega should work, you can change `DT_ENV=prod` to `DT_ENV=selfhosted` and not rename the file
> 
> here it's modified :
> 
> ```
> version: '3.3'
> services:
>   app:
>     build:
>       context: .
>       dockerfile: Dockerfile
>     container_name: donetick-core
>     restart: unless-stopped
>     volumes:
>       - ./data:/usr/src/app/data
>       - ./config:/config
>     ports:
>       - "2021:2021"
>     environment:
>       - DT_ENV=selfhosted
>     hostname: donetick-core
>     command: ["/donetick"]  
> networks:
>   default:
> ```

@meauxt One other thing, if you could be so kind... I’d like to be able to change the jwt to something other than “secret”. Doing so, causes an invalid signature error.
```
2024-11-23T04:53:12.274Z        info    authorization/middleware.go:120 middleware.jwt.Unauthorizedcode401messagesignature is invalid
```

**Comment by Tarow** [comment]
For anyone else coming along, this works fine for me using the prebuild image (since i don't want to build from source):
```yaml
services:
  donetick:
    image: donetick/donetick
    container_name: donetick
    restart: unless-stopped
    ports:
      - 2021:2021
    volumes:
      - ./data:/usr/src/app/data
      - ./config:/config
    environment:
      - DT_ENV=selfhosted
```

with the `./config/selfhosted.yaml` content taken/modified from here: https://github.com/donetick/donetick/blob/main/config/selfhosted.yaml
